name: Playwright Tests
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
jobs:
  test:
    if : github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - name: Install dependencies
        run: npm ci --legacy-peer-deps && npx playwright install --with-deps
      - name: Run tests
        run: npx platwright test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
